config/routes.rb
Cityquest::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" },  :skip => [:sessions] do 
    get 'sign_in',  :to => 'home#index', :as => :new_user_session
    get 'sign_out', :to => 'home#destroy', :as => :destroy_user_session
  end

  devise_scope :users do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end

  root :to => 'home#index'

  resources :users

  namespace :api do
    resource :users
  end

  namespace :mobile do
    root :to => 'profiles#show'
    resource :profile do
      get :quests, :on => :member
    end
    resources :quests do
      get :join, :on => :member
    end
  end

  namespace :admin do
    root :to => 'trails#index'
    resources :trails do 
      resources :trail_locations
    end
    resources :locations do 
      get :search
    end
  end

end

app/models/asset.rb
class Asset < ActiveRecord::Base
end

app/models/foursquare.rb
class Foursquare

  def self.try(latitude,longitude)
    conn = ::FaradayStack.build 'https://api.foursquare.com/v2'
    conn.builder.insert_before ::FaradayStack::ResponseJSON, ::Faraday::Response::Mashify

    # JSON resource
    resp = conn.get "venues/search?client_id=#{Settings.foursquare.key}&client_secret=#{Settings.foursquare.secret}&ll=#{latitude},#{longitude}"
    resp.body
  end

  def self.search(query)

    # Hardcode to KK
    latitude = 5.9620886
    longitude = 116.0804111
    conn = ::FaradayStack.build 'https://api.foursquare.com/v2'
    conn.builder.insert_before ::FaradayStack::ResponseJSON, ::Faraday::Response::Mashify

    resp = conn.get "venues/search?client_id=#{Settings.foursquare.key}&client_secret=#{Settings.foursquare.secret}&query=#{query}&radius=100000&&ll=#{latitude},#{longitude}"
    results = resp.body
    locations = []
    results.response.groups[0].items.each {|r| locations << {:name => r.name, :longitude => r.location.lng, :latitude => r.location.lat } }
    locations
  end
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :address, :latitude, :longitude, :image_url

  has_many :trail_locations
  has_many :trails, :through => :trail_locations

  geocoded_by :address
  after_validation :geocode, :if => :address_changed?  


  def self.to_dropdown
    Location.all.map {|l| [l.address, l.id]}
  end

end

app/models/quest.rb
class Quest < ActiveRecord::Base
  belongs_to :user
  belongs_to :trail
  belongs_to :trail_location

  validates :trail_location_id, :trail_id, :user_id, :presence => true
  validates :trail_location_id, :uniqueness => { :scope => [:trail_id, :user_id] }
 

  scope :done, where(:done => true)
  scope :todo, where(:done => false)
end

app/models/trail.rb
class Trail < ActiveRecord::Base

  attr_accessible :name, :description, :featured
  has_many :trail_locations
  has_many :locations, :through => :trail_locations

  scope :featured, where(:featured => true)

end

app/models/trail_location.rb
class TrailLocation < ActiveRecord::Base

  belongs_to :trail
  belongs_to :location
  has_many   :quests

  validates :location_id, :trail_id, :presence => true
  validates :location_id, :uniqueness => { :scope => :trail_id }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable

  has_many :quests
  has_many :trails, :through => :quests

  # Setup accessible (or protected) attributes for your model

  def self.find_for_facebook_oauth(access_token, signed_in_resource=nil)
    data = access_token.extra.raw_info
    if user = User.find_by_email(data.email)
      user
    else # Create a user with a stub password. 
      user = User.create!(:email => data.email, :encrypted_password => Devise.friendly_token[0,20]) 
    end
    user.update_from_omniauth(access_token)
    user
  end


  attr_accessible :email, :name, :display_name, :gender, :dob, :location, :password, :password_confirmation

  def update_from_omniauth(auth)    
    self.provider = auth['provider']
    self.uid = auth['uid']
    self.token = auth['credentials']['token']
    self.raw_data = auth.to_json
    self.name   = auth['info']['name']
    self.nick   = auth['info']['nickname']
    self.gender = auth['extra']['raw_info']['gender']
    self.dob    = auth['extra']['raw_info']['birthday']
    self.location =  auth['extra']['raw_info']['location']['name']
    self.avatar_url = auth['info']['image']
    save
  end

 def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["user_hash"]
        user.email = data["email"]
      end
    end
  end

end

app/controllers/admin/locations_controller.rb
class Admin::LocationsController < AdminController

  inherit_resources
  respond_to :html
  actions :all, except: [:show]

  def index  
    if params[:search].present?  
      @locations = Location.near(params[:search], 2, :order => :distance)  
    else  
      @locations = Location.all  
    end  
  end


  def new
    if params[:query].present?  
      @search_results = Foursquare.search(params[:query])
    end
    super
  end
  
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout "admin"
  http_basic_authenticate_with :name => "admin", :password => "admin"
  skip_before_filter :authenticate_user!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery    # Disable for API to work

  before_filter :authenticate_user!

  # Overwriting the sign_out redirect path method
  def after_sign_in_path_for(resource_or_scope)
    root_path
  end

  def after_sign_out_path_for(resource_or_scope)
    root_path
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :authenticate_user!

  def index
    @featured_trail = Trail.featured.first
  end

  def destroy
    sign_out :user
    redirect_to root_path
  end
end

app/controllers/mobile/locations_controller.rb
class Mobile::LocationsController < MobileController

  def index
    
  end

end

app/controllers/mobile_controller.rb
class MobileController < ApplicationController
  layout 'mobile'
end

app/controllers/trails_controller.rb
class TrailsController < ApplicationController

  def index
    
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/admin/locations_helper.rb
module Admin::LocationsHelper
end

app/helpers/admin/trails_helper.rb
module Admin::TrailsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def alert_messages
    return if flash.blank?
    alerts = ""
    flash.each do |type, message|
      alerts += content_tag(:div, :class => "alert-message #{type}") do 
        link_to("&#215;".html_safe, "#", :class => "close") + content_tag(:p, message)
      end
    end
    alerts.html_safe
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mobile/home_helper.rb
module Mobile::HomeHelper
end

app/helpers/mobile/locations_helper.rb
module Mobile::LocationsHelper
end

app/helpers/mobile_helper.rb
module MobileHelper
end

app/helpers/trails_helper.rb
module TrailsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/locations/_location.html.erb
<tr>
  <td><h3><%= link_to location.address, edit_admin_location_path(location) %></h3></td>
  <td class="action-links"><%= link_to "Edit", edit_admin_location_path(location), :class => "btn" %></td>
</tr>

app/views/admin/locations/edit.html.erb
<%- content_for :page_title, "Edit Location" %>

<%- content_for :sidebar do -%>
   <p><%= link_to "Delete this location", admin_location_path(@location), :method => :delete, :confirm => "Are you sure?", :class => "btn danger" %></p>
<% end -%>

<h1>Edit Location</h1>

<%= simple_form_for [:admin, @location] do |f| %>

  <%= f.input :address, :input_html => { :class => "span8" } %>
  <%= f.input :latitude, :input_html => { :class => "span8" } %>
  <%= f.input :longitude, :input_html => { :class => "span8" } %>
  <%= f.input :image_url, :input_html => { :class => "span8" } %>

  <div class="offset-form">
    <%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=15&markers=#{@location.latitude}%2C#{@location.longitude}" %>
  </div>


  <div class="actions">
    <%= f.button :submit, :class => "primary btn" %>&nbsp;
  </div>

<h3>Nearby Locations</h3>  
<ul>  
<% for location in @location.nearbys(5) %>  
  <li><%= link_to location.address, edit_admin_location_path(location) %> ↵  
    (<%= location.distance.round(2) %> miles)</li>  
<% end %>  
</ul>  

<% end %>

app/views/admin/locations/index.html.erb
<%- content_for :page_title, "Locations" %>

<%- content_for :sidebar do -%>
  <%= link_to "Create a new location", new_admin_location_path, :class => "btn success" %>
<% end -%>

<h1>Locations</h1>

<%= form_tag admin_locations_path, :method => :get do %>  
  <p>  
    <%= text_field_tag :search, params[:search] %>  
    <%= submit_tag "Search near (2 Miles)", :name => nil %>  
<% end %>

<table class="zebra-striped">
  <thead>
    <tr>
      <th>Location Name</th>
      <th></th>
    </tr>
  </thead>
  <%= render @locations %>
</table>

app/views/admin/locations/new.html.erb
<%- content_for :page_title, "New Location" %>

<%- content_for :sidebar do -%>
  
<% end -%>

<h1>New Location</h1>

<%= simple_form_for [:admin, @location] do |f| %>

  <%= f.input :address, :input_html => { :class => "span8" } %>
  <%= f.input :latitude, :input_html => { :class => "span8" } %>
  <%= f.input :longitude, :input_html => { :class => "span8" } %>
  <%= f.input :image_url, :input_html => { :class => "span8" } %>

  <div class="actions">
    <%= f.button :submit, :class => "primary btn" %>&nbsp;
  </div>

<% end %>


<%=  form_for [:admin, @location], :url => new_admin_location_path, :method => :get  do |f| %>
  <%= text_field_tag :query %>
  <%= f.submit :search, :class => "primary btn" %>&nbsp;
<% end %>


<%= for result in @search_results do %>
  <p><%= result[:name] %> <%= "[#{result[:latitude]}, #{result[:longitude]}]" %></p>
<% end unless @search_results.blank? %>