config/routes.rb
Cityquest::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" },  :skip => [:sessions] do 
    get 'sign_in',  :to => 'home#index', :as => :new_user_session
    get 'sign_out', :to => 'home#destroy', :as => :destroy_user_session
  end

  devise_scope :users do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end

  root :to => 'home#index'

  resources :users

  namespace :api do
    resource :users
  end

  namespace :mobile do
    root :to => 'profiles#show'
    resource :profile do
      get :quests, :on => :member
    end
    resources :quests do
      get :join, :on => :member
    end
  end

  namespace :admin do
    root :to => 'trails#index'
    resources :trails do 
      resources :trail_locations
    end
    resources :locations do 
      get :search
    end
  end

end

app/controllers/mobile/home_controller.rb
class Mobile::HomeController < ApplicationController
  skip_before_filter :authenticate_user!
end

app/controllers/mobile/locations_controller.rb
class Mobile::LocationsController < MobileController

  def index
    
  end

end

app/controllers/mobile/profiles_controller.rb
class Mobile::ProfilesController < MobileController


  def show
    @trail = Trail.featured.first
    @locations = @trail.locations

    @nearby = @trail.locations.near([session[:latitude].to_f, session[:longitude].to_f], 2).first
    @nearby = Location.first if @nearby.blank?
  end

  def quests
    @trails = Trail.all
  end

end

app/controllers/mobile/quests_controller.rb
class Mobile::QuestsController < MobileController

  before_filter :find_quest, :only => [:show]

  def index
    
  end

  def join
    @trail = Trail.find(params[:id])
    @trail.trail_locations.each do |tl|
      current_user.quests.create(:name => @trail.name, :trail_id => @trail.id, :trail_location_id => tl.id) 
    end
    flash[:success] = "You can start your quest #{@trail.name}"
    redirect_to mobile_profile_path
  end

  def show
    @user = @quest.user
    @location = @quest.trail_location.location
  end

  def update
    # Check if you are near location
    # @location = @quest.location_trail.location
    # @nearby = Location.find(:all, :origin =>[session[:latitude],session[:longitude]], :within=>1)
    # success = @nearby.map(&:id).include?(@location.id)
    @location = Location.find(params[:id])
    @trail_location = @location.trail_locations[0]
  
    quest = current_user.quests.find_or_create_by_name_and_trail_id_and_trail_location_id(:name => @trail_location.trail.name, :trail_id => @trail_location.trail.id, :trail_location_id => @trail_location.id, :done => true)   
    # @quest.update_attribute(:done, true)
    flash[:success] = "You have checked in to #{@location.address}"
    redirect_to mobile_quest_path(quest)
  end

protected

  def find_quest
     @quest = current_user.quests.find(params[:id])
  end

end

app/controllers/mobile_controller.rb
class MobileController < ApplicationController
  layout 'mobile'
end

app/helpers/mobile/home_helper.rb
module Mobile::HomeHelper
end

app/helpers/mobile/locations_helper.rb
module Mobile::LocationsHelper
end

app/helpers/mobile/profiles_helper.rb
module Mobile::ProfilesHelper
end

app/helpers/mobile_helper.rb
module MobileHelper
end

app/views/mobile/profiles/_location.html.erb
<div class="location">
  <div class="map">
    <%= image_tag "http://maps.google.com/maps/api/staticmap?size=120x100&sensor=false&zoom=15&markers=#{location.latitude}%2C#{location.longitude}" %>
  </div>
  <div class="info">
    <h3><%= location.address %></h3>
    <p><%= location.distance_from([session[:latitude].to_f,session[:longitude].to_f]).round(2) %> miles</p>
  </div>
</div>

app/views/mobile/profiles/_trail.html.erb
<div class="location">
  <div class="info row">
    <div class="span9">
      <h3><%= trail.name %></h3>
    </div>
    <div class="span3">
      <%= link_to "Join", join_mobile_quest_path(trail.id), :class => "btn primary success" %>
    </div>
  </div>
</div>

app/views/mobile/profiles/quests.html.erb
<%- content_for :page_title, "Available Quests" %>

<div class="more">
  <h3>Quests Available</h3>
</div>

<%= render :partial => "trail", :collection => @trails %>

app/views/mobile/profiles/show.html.erb
<%- content_for :page_title, @trail.name %>

<div class="profile">
  <%= link_to image_tag(current_user.avatar_url), user_path(current_user) %>
  <p><%= current_user.name %><br />
  <span>Seasoned Travel Extraordinaire</span></p>
</div>

<div class="checkin">
  <p>Currently near</p>
  <h3><%= @nearby.address %></h3>
  <%= link_to "Check In Here", mobile_quest_path(:id => @nearby.id), :method => :put, :class => "btn success large" %>
</div>

<ul class="activity media-grid">
  <li>
    <a href="#">
      <%= image_tag("http://maps.google.com/maps/api/staticmap?size=280x200&sensor=false&zoom=15&markers=#{@nearby.latitude}%2C#{@nearby.longitude}") %>
    </a>
  </li>
</ul>

<div class="more">
  <h3><%= @locations.size %> more to complete Quest</h3>
</div>

<%= render :partial => "location", :collection => @locations %>