config/routes.rb
Cityquest::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" },  :skip => [:sessions] do 
    get 'sign_in',  :to => 'home#index', :as => :new_user_session
    get 'sign_out', :to => 'home#destroy', :as => :destroy_user_session
  end

  devise_scope :users do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end

  root :to => 'home#index'

  resources :users

  namespace :api do
    resource :users
  end

  namespace :mobile do
    root :to => 'profiles#show'
    resource :profile do
      get :quests, :on => :member
    end
    resources :quests do
      get :join, :on => :member
    end
  end

  namespace :admin do
    root :to => 'trails#index'
    resources :trails do 
      resources :trail_locations
    end
    resources :locations do 
      get :search
    end
  end

end

app/models/asset.rb
class Asset < ActiveRecord::Base
end

app/models/foursquare.rb
class Foursquare

  def self.try(latitude,longitude)
    conn = ::FaradayStack.build 'https://api.foursquare.com/v2'
    conn.builder.insert_before ::FaradayStack::ResponseJSON, ::Faraday::Response::Mashify

    # JSON resource
    resp = conn.get "venues/search?client_id=#{Settings.foursquare.key}&client_secret=#{Settings.foursquare.secret}&ll=#{latitude},#{longitude}"
    resp.body
  end

  def self.search(query)

    # Hardcode to KK
    latitude = 5.9620886
    longitude = 116.0804111
    conn = ::FaradayStack.build 'https://api.foursquare.com/v2'
    conn.builder.insert_before ::FaradayStack::ResponseJSON, ::Faraday::Response::Mashify

    resp = conn.get "venues/search?client_id=#{Settings.foursquare.key}&client_secret=#{Settings.foursquare.secret}&query=#{query}&radius=100000&&ll=#{latitude},#{longitude}"
    results = resp.body
    locations = []
    results.response.groups[0].items.each {|r| locations << {:name => r.name, :longitude => r.location.lng, :latitude => r.location.lat } }
    locations
  end
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :address, :latitude, :longitude, :image_url

  has_many :trail_locations
  has_many :trails, :through => :trail_locations

  geocoded_by :address
  after_validation :geocode, :if => :address_changed?  


  def self.to_dropdown
    Location.all.map {|l| [l.address, l.id]}
  end

end

app/models/quest.rb
class Quest < ActiveRecord::Base
  belongs_to :user
  belongs_to :trail
  belongs_to :trail_location

  validates :trail_location_id, :trail_id, :user_id, :presence => true
  validates :trail_location_id, :uniqueness => { :scope => [:trail_id, :user_id] }
 

  scope :done, where(:done => true)
  scope :todo, where(:done => false)
end

app/models/trail.rb
class Trail < ActiveRecord::Base

  attr_accessible :name, :description, :featured
  has_many :trail_locations
  has_many :locations, :through => :trail_locations

  scope :featured, where(:featured => true)

end

app/models/trail_location.rb
class TrailLocation < ActiveRecord::Base

  belongs_to :trail
  belongs_to :location
  has_many   :quests

  validates :location_id, :trail_id, :presence => true
  validates :location_id, :uniqueness => { :scope => :trail_id }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable

  has_many :quests
  has_many :trails, :through => :quests

  # Setup accessible (or protected) attributes for your model

  def self.find_for_facebook_oauth(access_token, signed_in_resource=nil)
    data = access_token.extra.raw_info
    if user = User.find_by_email(data.email)
      user
    else # Create a user with a stub password. 
      user = User.create!(:email => data.email, :encrypted_password => Devise.friendly_token[0,20]) 
    end
    user.update_from_omniauth(access_token)
    user
  end


  attr_accessible :email, :name, :display_name, :gender, :dob, :location, :password, :password_confirmation

  def update_from_omniauth(auth)    
    self.provider = auth['provider']
    self.uid = auth['uid']
    self.token = auth['credentials']['token']
    self.raw_data = auth.to_json
    self.name   = auth['info']['name']
    self.nick   = auth['info']['nickname']
    self.gender = auth['extra']['raw_info']['gender']
    self.dob    = auth['extra']['raw_info']['birthday']
    self.location =  auth['extra']['raw_info']['location']['name']
    self.avatar_url = auth['info']['image']
    save
  end

 def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["user_hash"]
        user.email = data["email"]
      end
    end
  end

end

app/controllers/admin/trails_controller.rb
class Admin::TrailsController < AdminController

  inherit_resources
  respond_to :html
  actions :all, except: [:show]

  def edit
    @trail_location = TrailLocation.new
    super
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout "admin"
  http_basic_authenticate_with :name => "admin", :password => "admin"
  skip_before_filter :authenticate_user!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery    # Disable for API to work

  before_filter :authenticate_user!

  # Overwriting the sign_out redirect path method
  def after_sign_in_path_for(resource_or_scope)
    root_path
  end

  def after_sign_out_path_for(resource_or_scope)
    root_path
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :authenticate_user!

  def index
    @featured_trail = Trail.featured.first
  end

  def destroy
    sign_out :user
    redirect_to root_path
  end
end

app/controllers/mobile_controller.rb
class MobileController < ApplicationController
  layout 'mobile'
end

app/controllers/trails_controller.rb
class TrailsController < ApplicationController

  def index
    
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/admin/locations_helper.rb
module Admin::LocationsHelper
end

app/helpers/admin/trails_helper.rb
module Admin::TrailsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def alert_messages
    return if flash.blank?
    alerts = ""
    flash.each do |type, message|
      alerts += content_tag(:div, :class => "alert-message #{type}") do 
        link_to("&#215;".html_safe, "#", :class => "close") + content_tag(:p, message)
      end
    end
    alerts.html_safe
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mobile/home_helper.rb
module Mobile::HomeHelper
end

app/helpers/mobile/locations_helper.rb
module Mobile::LocationsHelper
end

app/helpers/mobile/profiles_helper.rb
module Mobile::ProfilesHelper
end

app/helpers/mobile_helper.rb
module MobileHelper
end

app/helpers/trails_helper.rb
module TrailsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/trails/_location.html.erb
<tr>
  <td><h3><%= location.address %></h3></td>
  <td class="action-links"><%= link_to "Delete", admin_trail_trail_location_path(trail, id), :method => :delete, :class => "btn danger", :confirm => "Are you sure?" %></td>
</tr>

app/views/admin/trails/_trail.html.erb
<tr>
  <td><h3><%= link_to trail.name, edit_admin_trail_path(trail) %></h3></td>
  <td class="action-links"><%= link_to "Edit", edit_admin_trail_path(trail), :class => "btn" %></td>
</tr>

app/views/admin/trails/edit.html.erb
<%- content_for :page_title, "Edit Trail" %>

<%- content_for :sidebar do -%>
  
  <p><%= link_to "Delete this trail", admin_trail_path(@trail), :method => :delete, :confirm => "Are you sure?", :class => "btn danger" %></p>

  <h3>Add location to trail</h3>
    <%= simple_form_for [:admin, @trail, @trail_location] do |f| %>
      <%= f.association :location, :collection => Location.to_dropdown, :prompt => "Choose a Location" %>
      <%= f.button :submit, :value => "Add Location", :class => "primary btn", :id => "new-trail-location" %>&nbsp;
    <% end %>  
<% end -%>

<h1>Edit Trail</h1>

<%= simple_form_for [:admin, @trail] do |f| %>

  <%= f.input :name, :input_html => { :class => "span8" } %>
  <%= f.input :description,  :input_html => { :class => "span8", :rows => 5 } %>
  <div class="input">
    <ul class="inputs-list">
      <li>
        <label>
          <input type="checkbox" name="trail[featured]" value="1" id="trail_featured" class="boolean optional" <% if @trail.featured? %>checked="true"<% end %>>
          <span>Feature Trail on Front Page</span>
        </label>
      </li>
    </ul>
  </div>
  <br />

  <div class="offset-form">
    <h3>Trail Locations</h3>
    <% if @trail.locations.blank? -%>
      <p>No locations added to this trail yet.</p>
    <% else %>
    <table class="zebra-striped">
      <%- for trail_location in @trail.trail_locations -%>
        <%= render :partial => "location", :locals => { :location => trail_location.location, :trail => trail_location.trail, :id => trail_location.id } %>
      <% end -%>
    </table>
    <% end %>
  </div>

  <div class="actions">
    <%= f.button :submit, :class => "primary btn" %>&nbsp;
  </div>

<% end %>

app/views/admin/trails/index.html.erb
<%- content_for :page_title, "Trails" %>

<%- content_for :sidebar do -%>
  <%= link_to "Create a new trail", new_admin_trail_path, :class => "btn success" %>
<% end -%>

<h1>Trails</h1>

<table class="zebra-striped">
  <thead>
    <tr>
      <th>Trail Name</th>
      <th></th>
    </tr>
  </thead>
  <%= render @trails %>
</table>

app/views/admin/trails/new.html.erb
<%- content_for :page_title, "New Trail" %>

<%- content_for :sidebar do -%>
  
<% end -%>

<h1>New Trail</h1>

<%= simple_form_for [:admin, @trail] do |f| %>

  <%= f.input :name, :input_html => { :class => "span8" } %>
  <%= f.input :description,  :input_html => { :class => "span8", :rows => 5 } %>

  <div class="actions">
    <%= f.button :submit, :class => "primary btn" %>&nbsp;
  </div>

<% end %>

app/views/trails/index.html.erb
<%- content_for :page_title, "Explore the city by completing quests" %>

<%- content_for :header do -%>
  <div class="header">
    <div class="container">
    <div class="logo">
      <span class="city">City</span><br />
      <div class="divider"></div>
      <span class="quest">QUEST</span>
    </div>
    <div class="desc">
      <h2>Go on a Quest &amp; Explore the City</h2>
      <p>Discover exciting venues and get rewarded for it!</p>
      <%= link_to image_tag("facebook_connect.png"), user_omniauth_authorize_path(:facebook) unless user_signed_in? %>
      Welcome <%= current_user.name %> <%= image_tag(current_user.avatar_url) if user_signed_in? %>
    </div>
    </div>
  </div>
<% end -%>

<%- content_for :footer do -%>
  <div class="footer">
    <div class="container">
      <div class="row">
        <div class="span-one-third">
          <h3>How does it work?</h3>
          <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>
        </div>
        <div class="span-one-third">
          <h3>Earn rewards while exploring!</h3>
          <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>
        </div>
        <div class="span-one-third">
          <h3>Hacked together by</h3>
          <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>
        </div>
      </div>
    </div>
  </div>
<% end -%>

<div class="content container">
  <div class="title">
    <h1>Today's Quest</h1>
  </div>

  <div class="images row">
    <div class="span-one-third image">
      <%= image_tag("quests/1.jpeg") %>
    </div>
    <div class="span-one-third image">
      <%= image_tag("quests/2.jpeg") %>
    </div>
    <div class="span-one-third image">
      <%= image_tag("quests/3.jpeg") %>
    </div>
  </div>

  <div class="quest">
    <h3>Food Frenzy!</h3>
    <p>6 Finger-licking Meals at 6 Awesome Restaurants</p>
  </div>

</div>