config/routes.rb
Cityquest::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" },  :skip => [:sessions] do 
    get 'sign_in',  :to => 'home#index', :as => :new_user_session
    get 'sign_out', :to => 'home#destroy', :as => :destroy_user_session
  end

  devise_scope :users do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end

  root :to => 'home#index'

  resources :users

  namespace :api do
    resource :users
  end

  namespace :mobile do
    root :to => 'profiles#show'
    resource :profile do
      get :quests, :on => :member
    end
    resources :quests do
      get :join, :on => :member
    end
  end

  namespace :admin do
    root :to => 'trails#index'
    resources :trails do 
      resources :trail_locations
    end
    resources :locations do 
      get :search
    end
  end

end

app/models/asset.rb
class Asset < ActiveRecord::Base
end

app/models/foursquare.rb
class Foursquare

  def self.try(latitude,longitude)
    conn = ::FaradayStack.build 'https://api.foursquare.com/v2'
    conn.builder.insert_before ::FaradayStack::ResponseJSON, ::Faraday::Response::Mashify

    # JSON resource
    resp = conn.get "venues/search?client_id=#{Settings.foursquare.key}&client_secret=#{Settings.foursquare.secret}&ll=#{latitude},#{longitude}"
    resp.body
  end

  def self.search(query)

    # Hardcode to KK
    latitude = 5.9620886
    longitude = 116.0804111
    conn = ::FaradayStack.build 'https://api.foursquare.com/v2'
    conn.builder.insert_before ::FaradayStack::ResponseJSON, ::Faraday::Response::Mashify

    resp = conn.get "venues/search?client_id=#{Settings.foursquare.key}&client_secret=#{Settings.foursquare.secret}&query=#{query}&radius=100000&&ll=#{latitude},#{longitude}"
    results = resp.body
    locations = []
    results.response.groups[0].items.each {|r| locations << {:name => r.name, :longitude => r.location.lng, :latitude => r.location.lat } }
    locations
  end
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :address, :latitude, :longitude, :image_url

  has_many :trail_locations
  has_many :trails, :through => :trail_locations

  geocoded_by :address
  after_validation :geocode, :if => :address_changed?  


  def self.to_dropdown
    Location.all.map {|l| [l.address, l.id]}
  end

end

app/models/quest.rb
class Quest < ActiveRecord::Base
  belongs_to :user
  belongs_to :trail
  belongs_to :trail_location

  validates :trail_location_id, :trail_id, :user_id, :presence => true
  validates :trail_location_id, :uniqueness => { :scope => [:trail_id, :user_id] }
 

  scope :done, where(:done => true)
  scope :todo, where(:done => false)
end

app/models/trail.rb
class Trail < ActiveRecord::Base

  attr_accessible :name, :description, :featured
  has_many :trail_locations
  has_many :locations, :through => :trail_locations

  scope :featured, where(:featured => true)

end

app/models/trail_location.rb
class TrailLocation < ActiveRecord::Base

  belongs_to :trail
  belongs_to :location
  has_many   :quests

  validates :location_id, :trail_id, :presence => true
  validates :location_id, :uniqueness => { :scope => :trail_id }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable

  has_many :quests
  has_many :trails, :through => :quests

  # Setup accessible (or protected) attributes for your model

  def self.find_for_facebook_oauth(access_token, signed_in_resource=nil)
    data = access_token.extra.raw_info
    if user = User.find_by_email(data.email)
      user
    else # Create a user with a stub password. 
      user = User.create!(:email => data.email, :encrypted_password => Devise.friendly_token[0,20]) 
    end
    user.update_from_omniauth(access_token)
    user
  end


  attr_accessible :email, :name, :display_name, :gender, :dob, :location, :password, :password_confirmation

  def update_from_omniauth(auth)    
    self.provider = auth['provider']
    self.uid = auth['uid']
    self.token = auth['credentials']['token']
    self.raw_data = auth.to_json
    self.name   = auth['info']['name']
    self.nick   = auth['info']['nickname']
    self.gender = auth['extra']['raw_info']['gender']
    self.dob    = auth['extra']['raw_info']['birthday']
    self.location =  auth['extra']['raw_info']['location']['name']
    self.avatar_url = auth['info']['image']
    save
  end

 def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["user_hash"]
        user.email = data["email"]
      end
    end
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout "admin"
  http_basic_authenticate_with :name => "admin", :password => "admin"
  skip_before_filter :authenticate_user!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery    # Disable for API to work

  before_filter :authenticate_user!

  # Overwriting the sign_out redirect path method
  def after_sign_in_path_for(resource_or_scope)
    root_path
  end

  def after_sign_out_path_for(resource_or_scope)
    root_path
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :authenticate_user!

  def index
    @featured_trail = Trail.featured.first
  end

  def destroy
    sign_out :user
    redirect_to root_path
  end
end

app/controllers/mobile_controller.rb
class MobileController < ApplicationController
  layout 'mobile'
end

app/controllers/trails_controller.rb
class TrailsController < ApplicationController

  def index
    
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def alert_messages
    return if flash.blank?
    alerts = ""
    flash.each do |type, message|
      alerts += content_tag(:div, :class => "alert-message #{type}") do 
        link_to("&#215;".html_safe, "#", :class => "close") + content_tag(:p, message)
      end
    end
    alerts.html_safe
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mobile/home_helper.rb
module Mobile::HomeHelper
end

app/helpers/mobile_helper.rb
module MobileHelper
end

app/helpers/trails_helper.rb
module TrailsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/shared/_nav.html.erb
<div class="topbar-wrapper" style="z-index: 5;">
    <div class="topbar" data-dropdown="dropdown">
      <div class="topbar-inner">
        <div class="container">
          <h3><%= link_to "CityQuest", admin_root_path %></h3>
          <ul class="nav">
            <li class="<%= "active" if controller.controller_name == 'trails' %>"><%= link_to "Trails", admin_trails_path %></li>
            <li class="<%= "active" if controller.controller_name == 'locations' %>"><%= link_to "Locations", admin_locations_path %></li>
          </ul>
          <ul class="nav secondary-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle">Hi Admin</a>
              <ul class="dropdown-menu">
                <li><%= link_to "Main Site", root_path %></li>
              </ul>
            </li>
          </ul>
        </div>
      </div><!-- /topbar-inner -->
    </div><!-- /topbar -->
  </div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield :page_title %> - Admin</title>
  <!-- Meta tags -->
  <%= yield :meta_tags %>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <link rel="stylesheet" media="all" href=""/>
  <%= stylesheet_link_tag    "admin" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render :partial => "admin/shared/nav" %>
  <div class="container">
    <div class="row">
      <div class="span12">
        <div class="content">
          <%= alert_messages %>
          <%= yield %>
        </div>
      </div>
      <div class="span4 sidebar">
        <%= yield :sidebar %>
      </div>
    </div>
    <div class="row">
      <div class="span12 footer">
        CityQuest was hacked together by <%= link_to "Flexnode Solutions", "http://flexnode.com" %>
      </div>
    </div>
  </div>

  <!--[if lt IE 7 ]>
    <script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.2/CFInstall.min.js"></script>
    <script>window.attachEvent("onload",function(){CFInstall.check({mode:"overlay"})})</script>
  <![endif]-->
  <%= javascript_include_tag "admin" %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield :page_title %></title>
  <!-- Meta tags -->
  <%= yield :meta_tags %>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <link rel="stylesheet" media="all" href=""/>
  <link href='http://fonts.googleapis.com/css?family=Rammetto+One' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="header">
    <div class="container">
    <div class="logo">
      <a href="/" class="city">City</a><br />
      <div class="divider"></div>
      <a href="/" class="quest">QUEST</a>

    </div>
    <div class="desc">
      <h2>Go on a Quest &amp; Explore the City</h2>
      <p>Discover exciting venues and get rewarded for it!</p>
      <%= link_to image_tag("facebook_connect.png"), user_omniauth_authorize_path(:facebook) unless user_signed_in? %>
      <% if user_signed_in? %>
        <div class="user_info">
          <%= link_to image_tag(current_user.avatar_url), user_path(current_user) %>
          <p>Welcome! <br /><%= current_user.name %></p>
        </div>
      <% end -%>
    </div>
    </div>
  </div>
  <%= yield %>
  
  <div class="footer">
    <div class="container">
      <div class="row">
        <div class="span-one-third">
          <h3>How does it work?</h3>
          <p>Download CityQUEST mobile app and begin your epic quest! Everyday we have fun and unique quest that will take you all around the city.</p>
        </div>
        <div class="span-one-third">
          <h3>Earn rewards while exploring!</h3>
          <p>As you explore the city, you will be rewarded with special discounts and promotions. All you need to do is show up at the right place and check-in!</p>
        </div>
        <div class="span-one-third">
          <h3>Built with...</h3>
          <p>Ruby on Rails, MySQL. Facebook Connect for signups/logins. Google Maps API for geocoding. Twitter Boostrap CSS.</p>
        </div>
      </div>
    </div>
  </div>
  <div class="copyright">
    Hacked together by Flexnode in 24 hours for Hackathon KK in ICT Fiesta, 27 Nov 2011
  </div>

  <!--[if lt IE 7 ]>
    <script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.2/CFInstall.min.js"></script>
    <script>window.attachEvent("onload",function(){CFInstall.check({mode:"overlay"})})</script>
  <![endif]-->
  <%= javascript_include_tag "application" %>
</body>
</html>

app/views/layouts/mobile.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cityquest</title>
  <link href='http://fonts.googleapis.com/css?family=Rammetto+One' rel='stylesheet' type='text/css'>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"/>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  <%= stylesheet_link_tag    "mobile" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "mobile" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="header">
    <%= yield :page_title %>
  </div>
  <div class="content">
    <%= yield %>
  </div>

</body>
</html>